"""
Example demonstrating the hierarchical template management system.

This script shows how to:
1. Define templates at different levels (FILE, CLASS, FUNCTION, BLOCK)
2. Register templates with the manager
3. Compose multiple templates into a complete service
4. Optimize the generated code
"""

import asyncio

from gong.templates.hierarchical import (
    CompositionStrategy,
    HierarchicalTemplateManager,
    ImportDependency,
    TemplateContent,
    TemplateLevel,
    TemplateMetadata,
    TemplateOptimizer,
    TemplateRequest,
    TemplateScope,
    Variable,
)


async def main() -> None:
    """Run the example."""
    print("=" * 80)
    print("Hierarchical Template Management System - Example")
    print("=" * 80)
    print()

    # Initialize the template manager
    manager = HierarchicalTemplateManager()

    # 1. Define FILE-level template for complete service
    file_template = TemplateContent(
        metadata=TemplateMetadata(
            id="file/fastapi_service",
            name="FastAPI Service File",
            description="Complete FastAPI microservice file",
            version="1.0.0",
            category="service",
            scope=TemplateScope(
                level=TemplateLevel.FILE, composition_strategy=CompositionStrategy.MERGE
            ),
            file_extension=".py",
            generates_classes=["ServiceApp"],
            import_dependencies=[
                ImportDependency(
                    module="fastapi", imports=["FastAPI", "HTTPException"], is_standard_library=False
                ),
                ImportDependency(module="uvicorn", imports=[], is_standard_library=False),
                ImportDependency(module="logging", imports=[], is_standard_library=True),
            ],
            tags=["fastapi", "microservice", "http"],
        ),
        template_code="""
# {{ service_name }} Microservice
# Generated by Gong Platform

app = FastAPI(
    title="{{ service_name }}",
    version="{{ version | default('1.0.0') }}",
    description="{{ description | default('Microservice API') }}"
)

# Setup logging
logger = logging.getLogger(__name__)

# Health check endpoint
@app.get("/health")
async def health_check():
    return {"status": "healthy", "service": "{{ service_name }}"}

# Service endpoints
{{ inject_endpoints }}

if __name__ == "__main__":
    uvicorn.run(
        app,
        host="{{ host | default('0.0.0.0') }}",
        port={{ port | default(8000) }}
    )
""",
    )

    # 2. Define FUNCTION-level template for API endpoints
    function_template = TemplateContent(
        metadata=TemplateMetadata(
            id="function/api_endpoint",
            name="API Endpoint",
            description="RESTful API endpoint function",
            version="1.0.0",
            category="api",
            scope=TemplateScope(
                level=TemplateLevel.FUNCTION,
                composition_strategy=CompositionStrategy.INJECT,
                target_injection_point="inject_endpoints",
            ),
            generates_functions=["{{ endpoint_name }}"],
            inputs=[
                Variable(name="endpoint_name", type="str", description="Function name"),
                Variable(name="path", type="str", description="API path"),
                Variable(name="method", type="str", description="HTTP method"),
                Variable(name="description", type="str", description="Endpoint description", required=False),
            ],
            outputs=[Variable(name="response", type="dict", description="JSON response")],
            tags=["api", "endpoint", "http"],
        ),
        template_code="""
@app.{{ method | lower }}("{{ path }}")
async def {{ endpoint_name }}(
    {%- if path_params %}
    {%- for param in path_params %}
    {{ param }}: str{{ "," if not loop.last }}
    {%- endfor %}
    {%- endif %}
):
    \"\"\"{{ description | default('API endpoint') }}\"\"\"
    logger.info("{{ endpoint_name }} called")
    
    {{ inject_logic }}
    
    return {"status": "success", "message": "{{ endpoint_name }} executed"}
""",
    )

    # 3. Define BLOCK-level template for business logic
    block_template = TemplateContent(
        metadata=TemplateMetadata(
            id="block/http_call",
            name="HTTP API Call Block",
            description="Make HTTP call to another service",
            version="1.0.0",
            category="io",
            scope=TemplateScope(
                level=TemplateLevel.BLOCK,
                composition_strategy=CompositionStrategy.INJECT,
                target_injection_point="inject_logic",
            ),
            import_dependencies=[
                ImportDependency(module="httpx", imports=[], is_standard_library=False)
            ],
            inputs=[
                Variable(name="target_service", type="str", description="Target service name"),
                Variable(name="target_path", type="str", description="Target API path"),
            ],
            tags=["http", "api-call", "io"],
        ),
        template_code="""
    # Call {{ target_service }} service
    async with httpx.AsyncClient() as client:
        response = await client.get("http://{{ target_service }}:8000{{ target_path }}")
        response.raise_for_status()
        data = response.json()
        logger.info(f"Received data from {{ target_service }}: {data}")
""",
    )

    # 4. Define BLOCK-level template for error handling
    error_template = TemplateContent(
        metadata=TemplateMetadata(
            id="block/error_handling",
            name="Error Handling Block",
            description="Comprehensive error handling with logging",
            version="1.0.0",
            category="control_flow",
            scope=TemplateScope(
                level=TemplateLevel.BLOCK, composition_strategy=CompositionStrategy.WRAP
            ),
            tags=["error-handling", "logging"],
        ),
        template_code="""
    try:
        {{ wrapped_code }}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in {{ function_name }}: {e}")
        raise HTTPException(status_code=500, detail=str(e))
""",
    )

    # Register all templates
    print("Registering templates...")
    await manager.register_template(file_template)
    await manager.register_template(function_template)
    await manager.register_template(block_template)
    await manager.register_template(error_template)
    print(f"✓ Registered {len(await manager.list_templates())} templates")
    print()

    # Create composition requests for a complete service
    print("Composing templates for UserService...")
    requests = [
        # File-level: Service structure
        TemplateRequest(
            template_id="file/fastapi_service",
            context={
                "service_name": "UserService",
                "version": "1.0.0",
                "description": "User management microservice",
                "host": "0.0.0.0",
                "port": 8001,
            },
        ),
        # Function-level: Get user endpoint
        TemplateRequest(
            template_id="function/api_endpoint",
            context={
                "endpoint_name": "get_user",
                "path": "/users/{user_id}",
                "method": "get",
                "description": "Get user by ID",
                "path_params": ["user_id"],
            },
        ),
        # Function-level: List users endpoint
        TemplateRequest(
            template_id="function/api_endpoint",
            context={
                "endpoint_name": "list_users",
                "path": "/users",
                "method": "get",
                "description": "List all users",
            },
        ),
        # Function-level: Create user endpoint
        TemplateRequest(
            template_id="function/api_endpoint",
            context={
                "endpoint_name": "create_user",
                "path": "/users",
                "method": "post",
                "description": "Create a new user",
            },
        ),
    ]

    # Compose templates
    composition_result = await manager.compose_templates(requests)
    print(f"✓ Composed {len(composition_result.composition_plan.steps)} templates")
    print(f"✓ Generated {len(composition_result.files)} file(s)")
    print()

    # Optimize the composition
    print("Optimizing generated code...")
    optimizer = TemplateOptimizer(manager)
    optimized = await optimizer.optimize_by_levels(
        composition_result.composition_plan, composition_result.files
    )
    print(f"✓ Optimized {len(optimized.files)} file(s)")
    print()

    # Display optimization logs
    print("Optimization Log:")
    for log_entry in optimized.optimization_log:
        print(f"  - {log_entry}")
    print()

    # Display generated files
    print("=" * 80)
    print("Generated Code")
    print("=" * 80)
    for file_path, optimized_file in optimized.files.items():
        print(f"\n{file_path}:")
        print("-" * 80)
        print(optimized_file.code)
        print("-" * 80)
        print(f"\nImports ({len(optimized_file.imports)}):")
        for imp in optimized_file.imports:
            if imp.imports:
                print(f"  from {imp.module} import {', '.join(imp.imports)}")
            else:
                print(f"  import {imp.module}")
        print()

    print("=" * 80)
    print("Template Composition Summary")
    print("=" * 80)
    print(f"Templates used: {len(composition_result.composition_plan.steps)}")
    print(f"Files generated: {len(optimized.files)}")
    print(f"Total imports optimized: {sum(len(f.imports) for f in optimized.files.values())}")
    print()
    print("Template levels used:")
    levels_used = set(step.level for step in composition_result.composition_plan.steps)
    for level in sorted(levels_used, key=lambda x: x.value):
        count = sum(1 for s in composition_result.composition_plan.steps if s.level == level)
        print(f"  - {level.value}: {count}")
    print()
    print("✓ Example completed successfully!")


if __name__ == "__main__":
    asyncio.run(main())
